auto: true

markdown: rdiscount
pygments: true
paginate: 8
permalink: /:title

title: Yooran's Bolg
url: http://yooranchen.com
feed: /atom.xml
author_info: <a href="http://yooranchen.com/">yooranchen</a>
